#!/usr/bin/env python3
"""Exchange WordPress.com application-password credentials for an OAuth token.

The script stores only the resulting bearer token and site metadata. It does not
persist the WordPress.com application password or OAuth client secret.
"""

from __future__ import annotations

import argparse
import getpass
import json
import os
from pathlib import Path
import ssl
import stat
import sys
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen


TOKEN_URL = "https://public-api.wordpress.com/oauth2/token"
ME_SITES_URL = "https://public-api.wordpress.com/rest/v1.1/me/sites"
DEFAULT_SITE = "christianthoughtsurvey.wordpress.com"
DEFAULT_TOKEN_FILE = ".secrets/wordpress.env"


def ssl_context() -> ssl.SSLContext | None:
    try:
        import certifi
    except ImportError:
        return None
    return ssl.create_default_context(cafile=certifi.where())


def env_or_prompt(name: str, prompt: str, *, secret: bool = False, default: str | None = None) -> str:
    value = os.environ.get(name)
    if value:
        return value
    if default:
        rendered = input(f"{prompt} [{default}]: ").strip()
        return rendered or default
    if secret:
        value = getpass.getpass(f"{prompt}: ").strip()
    else:
        value = input(f"{prompt}: ").strip()
    if not value:
        raise SystemExit(f"Missing required value: {name}")
    return value


def post_form(url: str, data: dict[str, str], headers: dict[str, str] | None = None) -> dict[str, Any]:
    body = urlencode(data).encode("utf-8")
    request = Request(
        url,
        data=body,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "Accept": "application/json",
            **(headers or {}),
        },
        method="POST",
    )
    return read_json(request)


def get_json(url: str, token: str) -> dict[str, Any]:
    request = Request(url, headers={"Authorization": f"Bearer {token}", "Accept": "application/json"})
    return read_json(request)


def read_json(request: Request) -> dict[str, Any]:
    try:
        with urlopen(request, timeout=30, context=ssl_context()) as response:
            payload = response.read().decode("utf-8")
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"WordPress.com API returned HTTP {exc.code}: {detail}") from exc
    except URLError as exc:
        raise SystemExit(f"Could not reach WordPress.com API: {exc.reason}") from exc
    try:
        data = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"WordPress.com API returned non-JSON response: {payload[:500]}") from exc
    if not isinstance(data, dict):
        raise SystemExit(f"WordPress.com API returned unexpected JSON: {payload[:500]}")
    return data


def find_site(token: str, target: str) -> dict[str, Any]:
    data = get_json(f"{ME_SITES_URL}?number=100", token)
    sites = data.get("sites")
    if not isinstance(sites, list):
        raise SystemExit("Could not read sites from WordPress.com account.")
    target_norm = normalize_site(target)
    for site in sites:
        if not isinstance(site, dict):
            continue
        candidates = {
            normalize_site(str(site.get("URL", ""))),
            normalize_site(str(site.get("domain", ""))),
            normalize_site(str(site.get("slug", ""))),
        }
        if target_norm in candidates:
            return site
    available = ", ".join(str(site.get("URL", "")) for site in sites if isinstance(site, dict))
    raise SystemExit(f"Could not find site {target!r} in this WordPress.com account. Available sites: {available}")


def normalize_site(value: str) -> str:
    value = value.strip().lower()
    value = value.removeprefix("https://").removeprefix("http://")
    value = value.removeprefix("www.")
    return value.rstrip("/")


def mask_token(token: str) -> str:
    if len(token) <= 12:
        return "*" * len(token)
    return f"{token[:6]}...{token[-6:]}"


def write_token_file(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/wpcom_get_token.py",
        "# Keep this file private. It is ignored by git.",
    ]
    lines.extend(f"{key}={shell_quote(value)}" for key, value in values.items())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--token-file", default=DEFAULT_TOKEN_FILE, help=f"default: {DEFAULT_TOKEN_FILE}")
    parser.add_argument("--site", default=os.environ.get("WPCOM_SITE", DEFAULT_SITE), help=f"default: {DEFAULT_SITE}")
    args = parser.parse_args()

    client_id = env_or_prompt("WPCOM_CLIENT_ID", "WordPress.com OAuth client ID")
    client_secret = env_or_prompt("WPCOM_CLIENT_SECRET", "WordPress.com OAuth client secret", secret=True)
    username = env_or_prompt("WPCOM_USERNAME", "WordPress.com username")
    app_password = env_or_prompt("WPCOM_APPLICATION_PASSWORD", "WordPress.com application password", secret=True)
    site_target = args.site

    token_data = post_form(
        TOKEN_URL,
        {
            "client_id": client_id,
            "client_secret": client_secret,
            "grant_type": "password",
            "username": username,
            "password": app_password,
        },
    )
    access_token = str(token_data.get("access_token", ""))
    token_type = str(token_data.get("token_type", "bearer"))
    if not access_token:
        raise SystemExit(f"Token exchange succeeded but no access_token was returned: {token_data}")

    site = find_site(access_token, site_target)
    site_id = str(site.get("ID", ""))
    site_url = str(site.get("URL", site_target))
    if not site_id:
        raise SystemExit(f"Found site but could not identify numeric site ID: {site}")

    token_file = Path(args.token_file)
    write_token_file(
        token_file,
        {
            "WPCOM_ACCESS_TOKEN": access_token,
            "WPCOM_TOKEN_TYPE": token_type,
            "WPCOM_SITE_ID": site_id,
            "WPCOM_SITE_URL": site_url,
            "WPCOM_SITE": site_target,
            "WPCOM_API_BASE": "https://public-api.wordpress.com",
        },
    )

    capabilities = site.get("capabilities", {})
    can_publish = capabilities.get("publish_posts") if isinstance(capabilities, dict) else None
    can_edit = capabilities.get("edit_posts") if isinstance(capabilities, dict) else None
    print(f"Wrote token file: {token_file}")
    print(f"Token: {mask_token(access_token)}")
    print(f"Site: {site_url} (ID {site_id})")
    print(f"Capabilities: edit_posts={can_edit}, publish_posts={can_publish}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
